routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);


Route::group(['middleware' => 'auth'], function (){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

    Route::group(['namespace' => 'Customers'], function(){
        Route::pattern('customer', '[0-9]+');
        Route::resource('customer', 'CustomersController');
    });
    Route::group(['namespace' => 'Providers'], function(){
        Route::pattern('provider', '[0-9]+');
        Route::resource('provider', 'ProvidersController');
    });
    Route::group(['namespace' => 'Designs'], function(){
        Route::pattern('design', '[0-9]+');
        Route::resource('design', 'DesignsController');
    });
    Route::group(['namespace' => 'Products'], function(){
        Route::pattern('product', '[0-9]+');
        Route::resource('product', 'ProductsController');
    });
    Route::group(['namespace' => 'Materials'], function(){
        Route::pattern('material', '[0-9]+');
        Route::resource('material', 'MaterialsController');
    });

    Route::group(['namespace' => 'Purchases'], function(){
        Route::pattern('purchase', '[0-9]+');
        Route::resource('purchase', 'PurchasesController');
    });
    Route::group(['namespace' => 'Orders'], function(){
        Route::pattern('order', '[0-9]+');
        Route::resource('order', 'OrdersController');
    });

    Route::group(['namespace' => 'Zones'], function(){
        Route::pattern('zone', '[0-9]+');
        Route::resource('zone', 'ZonesController');
    });

    Route::group(['namespace' => 'Employees'], function(){
        Route::pattern('employee', '[0-9]+');
        Route::resource('employee', 'EmployeesController');
    });

    Route::get('/reports', ['as' => 'reports', 'uses' => 'Reports\ReportsController@index']);
    Route::group(['namespace' => 'Batchs'], function(){
        Route::pattern('batch', '[0-9]+');
        Route::resource('batch','BatchsController');
    });

});

app/Design.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Design extends Model
{
    protected $fillable = [
        'name',
        'code'
    ];

    public function materials(){
        return $this->belongsToMany('App\Material', 'design_materials');
    }

    public function details()
    {
        return $this->hasMany('App\DesignMaterial');
    }
    public function products()
    {
        return $this->hasMany('App\Product');
    }

}

app/Http/Controllers/Designs/DesignsController.php
<?php

namespace App\Http\Controllers\Designs;

use App\Design;
use App\DesignMaterial;
use App\Material;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class DesignsController extends Controller
{
    protected $rules = [
        'name' => 'required|max:100',
        'code' => 'required|max:20'
    ];
    public $details = [];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $designs = Design::where(DB::raw('CONCAT(name, code)'),'LIKE','%'.$request->filter.'%')->get();
        return view('backend.designs.index', compact('designs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if(session('details') == null){
            session(['details' => []]);
        }
        $this->details = session('details');
        $details = $this->details;
        $materials = Material::all();
        return view('backend.designs.create', compact('materials','details'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       if($request->has('insert')){
           $this->validate($request, $this->rules);
           $this->validate($request, ['code' => 'unique:designs,code']);
           $design = new Design();
           $design->fill($request->all());
           $design->save();
           $details = session('details');
           foreach ($details as $detail){
               $detail->design_id = $design->id;
               $detail->save();
           }
           session(['details' => []]);
           return redirect()->back()->with('success', 'Diseño guardado exitosamente');
       }
       else if($request->has('add')){
           $this->validate($request, ['quantity' => 'required|numeric|min:1', 'material_id' => 'required']);
           $detail = new DesignMaterial();
           $detail->quantity = $request->quantity;
           $detail->material_id = $request->material_id;
           $this->details = session('details');
           foreach ($this->details as $d){
               if($d->material_id == $detail->material_id){
                   $d->quantity += $detail->quantity;
                   session(['details' => $this->details]);
                   return redirect()->back()->withInput();
               }
           }
           session()->push('details', $detail);
           return redirect()->back()->withInput();
       } else if($request->has('quit')){
           $this->details = session('details');
           unset($this->details[$request->id]);
           $this->details = array_values($this->details);
           session(['details' => $this->details]);
           return redirect()->back()->withInput();
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $design = Design::find($id);
        $details = DesignMaterial::where('design_id', $id)->get();
        $materials = Material::all();
        session(['detailsEdit' => $details]);
        return view('backend.designs.edit', compact('design', 'details', 'materials'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->has('update')){
            $this->validate($request, $this->rules);
            $design = Design::find($id);
            $design->fill($request->all());
            $design->status = $request->status ? 1 : 0;
            $design->save();
            return redirect()->back()->with('success', 'Diseño modificado exitosamente');
        }
        else if($request->has('add')){
            $this->validate($request, ['quantity' => 'required|numeric|min:1', 'material_id' => 'required']);
            $design = Design::find($id);
            foreach($design->details as $d){
                if($d->material_id == $request->material_id){
                    $d->quantity += $request->quantity;
                    $d->save();
                    return redirect()->back()->with('success', 'Detalle modificado exitosamente');
                }
            }
            $detail = new DesignMaterial();
            $detail->quantity = $request->quantity;
            $detail->material_id = $request->material_id;
            $detail->design_id = $id;
            $detail->save();
            return redirect()->back()->with('success', 'Detalle agregado exitosamente');
        }
        else if($request->has('quit')){
            $details = session('detailsEdit');
            $detail = $details[$request->id];
            $detail->delete();
            return redirect()->back()->with('success', 'Detalle eliminado exitosamente');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/designs/create.blade.php
@extends('generals.main')
@section('content')
    <h1>Ingresar Diseño</h1>

    {{Form::open(['route' => 'design.store', 'class' => 'form', 'mehtod' => 'POST'])}}
        @include('backend.designs.partials.inputs')
        <div class="row">
            <div class="col-lg-4">
                <select class="form-control" name="material_id">
                    @foreach($materials as $material)
                        <option value="{{$material->id}}">{{$material->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-4">
                <input type="text"  class="form-control" name="quantity" placeholder="Cantidad">
            </div>
            <div class="col-lg-4">
                <input type="submit" name="add" value="Agregar" class="btn btn-primary">
            </div>
            @include('backend.designs.partials.tableDetails')
        </div>







    <input type="submit" name="insert" value="Guardar" class="btn btn-lg btn-success">
    {{Form::close()}}


@endsection

resources/views/backend/designs/edit.blade.php
@extends('generals.main')
@section('content')
    <h1>Editar Diseño</h1>

    <div class="card">
        {{Form::open(['route' => ['design.update', $design->id], 'class' => 'form', 'method' => 'PUT'])}}

            @include('backend.designs.partials.inputs')
            <div class="col-lg-4">
                <select class="form-control" name="material_id">
                    @foreach($materials as $material)
                        <option value="{{$material->id}}">{{$material->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-4">
                <input type="text"  class="form-control" name="quantity" placeholder="Cantidad">
            </div>
            <div class="col-lg-4">
                <input type="submit" name="add" value="Agregar" class="btn btn-primary">
            </div>
            @include('backend.designs.partials.tableDetails')
            <input type="submit" value="Guardar" class="btn btn-lg btn-success" name="update">

        {{Form::close()}}
    </div>

@endsection
@section('extra-js')
    <script type="text/javascript">
        /*$('[name="quit_form"]').one('submit', function(e){
            e.preventDefault();
            $.confirm({
                theme: 'supervan',
                title: 'Confirmar',
                content: 'Ejemplo',
                buttons: {
                    cancel: {
                        text: 'Cancelar',
                        action: function () {
                        }
                    },
                    confirm: {
                        text: 'Confirmar',
                        action: function () {
                        }
                    }
                }
            });
            //$(this).submit();
        });*/
    </script>
@endsection

resources/views/backend/designs/index.blade.php
@extends('generals.main')
@section('search')
    {{Form::open(['route' => 'design.index', 'method' => 'get'])}}
    <input type="text" placeholder="Busqueda..."  name="filter">
    <input type="submit" value="">
    {{Form::close()}}
@endsection
@section('content')
    <h1>Diseños</h1>
    <div class="col-lg-6">
       <br><a href="{{route('design.create')}}"><button class="btn btn-lg btn-success">Nuevo</button></a><br><br>
    </div>
    @include('backend.designs.partials.table')
@endsection