routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);


Route::group(['middleware' => 'auth'], function (){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

    Route::group(['namespace' => 'Customers'], function(){
        Route::pattern('customer', '[0-9]+');
        Route::resource('customer', 'CustomersController');
    });
    Route::group(['namespace' => 'Providers'], function(){
        Route::pattern('provider', '[0-9]+');
        Route::resource('provider', 'ProvidersController');
    });
    Route::group(['namespace' => 'Designs'], function(){
        Route::pattern('design', '[0-9]+');
        Route::resource('design', 'DesignsController');
    });
    Route::group(['namespace' => 'Products'], function(){
        Route::pattern('product', '[0-9]+');
        Route::resource('product', 'ProductsController');
    });
    Route::group(['namespace' => 'Materials'], function(){
        Route::pattern('material', '[0-9]+');
        Route::resource('material', 'MaterialsController');
    });

    Route::group(['namespace' => 'Purchases'], function(){
        Route::pattern('purchase', '[0-9]+');
        Route::resource('purchase', 'PurchasesController');
    });
    Route::group(['namespace' => 'Orders'], function(){
        Route::pattern('order', '[0-9]+');
        Route::resource('order', 'OrdersController');
    });

    Route::group(['namespace' => 'Zones'], function(){
        Route::pattern('zone', '[0-9]+');
        Route::resource('zone', 'ZonesController');
    });

    Route::group(['namespace' => 'Employees'], function(){
        Route::pattern('employee', '[0-9]+');
        Route::resource('employee', 'EmployeesController');
    });

    Route::get('/reports', ['as' => 'reports', 'uses' => 'Reports\ReportsController@index']);
    Route::group(['namespace' => 'Batchs'], function(){
        Route::pattern('batch', '[0-9]+');
        Route::resource('batch','BatchsController');
    });

});

app/Employees.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
    protected $fillable=[
        'name','firstname','lastname'
    ];
}

app/Http/Controllers/Employees/EmployeesController.php
<?php

namespace App\Http\Controllers\Employees;

use App\Employees;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class EmployeesController extends Controller
{
     protected $rules = [
         'name' => 'required|max:50',
         'firstname' => 'required|max:70',
         'lastname' => 'required|max:70'
     ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$employees = Employees::all();
        $employees = Employees::where(DB::raw('CONCAT(name,firstname, lastname)'),'LIKE','%'.$request->filter.'%')->get();
        return view('backend.employees.index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->rules);
        $employees = new Employees();
        $employees->fill($request->all());
        $employees->save();
        return redirect()->back()->with('success','Empleado guardado éxitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function show(Employees $employees)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employees = Employees::find($id);
        return view('backend.employees.edit',compact('employees'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->rules);
        $employees = Employees::find($id);
        $employees->fill($request->all());
        $employees->save();
        return redirect()->back()->with('success','Empleado modificado éxitorsamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Employees::destroy($id);
        return redirect()->back()->with('success', 'Empleado eliminado exitosamente');
    }
}

resources/views/backend/employees/create.blade.php
@extends('generals.main')
@section('content')
    <h1>Ingresar Empleado</h1>

    <div class="card">
        {{Form::open(['route' => ['employee.store'], 'class' => 'form', 'method' => 'post'])}}

        @include('backend.employees.partials.inputs')
        <input type="submit" value="Guardar" class="btn btn-lg btn-success">

        {{Form::close()}}
    </div>
    @endsection

resources/views/backend/employees/edit.blade.php
@extends('generals.main')
@section('content')
    <h1>Editar Empleado</h1>
    {{Form::open(['route' => ['employee.update', $employees->id], 'class' => 'form', 'method' => 'put'])}}

    @include('backend.employees.partials.inputs')
    <input type="submit" value="Guardar" class="btn btn-lg btn-success">

    {{Form::close()}}
    @endsection

resources/views/backend/employees/index.blade.php
@extends('generals.main')
@section('search')
    {{Form::open(['route' => 'employee.index','method' => 'get'])}}
    <input type="text" placeholder="Busqueda..."  name="filter">
    <input type="submit" value="">
    {{Form::close()}}
@endsection
@section('content')
    <h1>Empleados</h1>
    <div class="col-lg-6">
        <br><a href="{{route('employee.create')}}"><button class="btn btn-lg btn-success">Nuevo</button></a><br><br>
    </div>
    @include('backend.employees.partials.table')
    @endsection