routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);


Route::group(['middleware' => 'auth'], function (){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

    Route::group(['namespace' => 'Customers'], function(){
        Route::pattern('customer', '[0-9]+');
        Route::resource('customer', 'CustomersController');
    });
    Route::group(['namespace' => 'Providers'], function(){
        Route::pattern('provider', '[0-9]+');
        Route::resource('provider', 'ProvidersController');
    });
    Route::group(['namespace' => 'Designs'], function(){
        Route::pattern('design', '[0-9]+');
        Route::resource('design', 'DesignsController');
    });
    Route::group(['namespace' => 'Products'], function(){
        Route::pattern('product', '[0-9]+');
        Route::resource('product', 'ProductsController');
    });
    Route::group(['namespace' => 'Materials'], function(){
        Route::pattern('material', '[0-9]+');
        Route::resource('material', 'MaterialsController');
    });

    Route::group(['namespace' => 'Purchases'], function(){
        Route::pattern('purchase', '[0-9]+');
        Route::resource('purchase', 'PurchasesController');
    });
    Route::group(['namespace' => 'Orders'], function(){
        Route::pattern('order', '[0-9]+');
        Route::resource('order', 'OrdersController');
    });

    Route::group(['namespace' => 'Zones'], function(){
        Route::pattern('zone', '[0-9]+');
        Route::resource('zone', 'ZonesController');
    });

    Route::group(['namespace' => 'Employees'], function(){
        Route::pattern('employee', '[0-9]+');
        Route::resource('employee', 'EmployeesController');
    });

    Route::get('/reports', ['as' => 'reports', 'uses' => 'Reports\ReportsController@index']);
    Route::group(['namespace' => 'Batchs'], function(){
        Route::pattern('batch', '[0-9]+');
        Route::resource('batch','BatchsController');
    });

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'status',
        'orderDate',
        'estimatedDate',
        'total',
        'customer_id'
    ];

    function customer(){
        return $this->belongsTo('App\Customer');
    }
    function details(){
        return $this->hasMany('App\OrderDetail');
    }
}

app/Http/Controllers/Orders/OrdersController.php
<?php

namespace App\Http\Controllers\Orders;

use App\Customer;
use App\Order;
use App\OrderDetail;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrdersController extends Controller
{
    protected $rules = [
        'orderDate' => 'required',
        'estimatedDate' => 'required|after:orderDate'
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        session(['order_first' => true]);
        $orders = Order::orderBy('orderDate', 'desc')
            ->get();
        return view('backend.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(session('order_first')){
            session(['orderDetails' => [], 'order_first' => null]);
        }
        $details = session('orderDetails');
        $total = 0;
        foreach ($details as $detail){
            $total += $detail->subtotal;
        }
        $products = Product::all();
        $customers = Customer::all();
        return view('backend.orders.create', compact('products', 'customers', 'details', 'total'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $details = session('orderDetails');

        if($request->has('insert')){
            $this->validate($request, $this->rules);
            $order = new Order();
            $order->fill($request->all());
            $order->save();
            foreach ($details as $detail){
                $detail->order_id = $order->id;
                $detail->save();
            }
            session(['orderDetails' => []]);
            return redirect()->back()->with('success', 'Orden guardada exitosamente');
        }
        else if($request->has('add')){
            $this->validate($request, ['quantity' => 'required|numeric|integer|min:1']);
            $detail = new OrderDetail();
            $detail->quantity = $request->quantity;
            $detail->product_id = $request->product_id;
            $detail->subtotal = $detail->product->price * $request->quantity;
            foreach ($details as $d){
                if($d->product_id == $detail->product_id){
                    $d->quantity += $detail->quantity;
                    $d->subtotal = $d->quantity * $d->product->price;
                    session(['orderDetails' => $details]);
                    return redirect()->back()->withInput();
                }
            }
            session()->push('orderDetails', $detail);
            return redirect()->back()->withInput();
        } else if($request->has('quit')){
            unset($details[$request->id]);
            $details = array_values($details);
            session(['orderDetails' => $details]);
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        $details = $order->details;
        $total = $order->total;
        $products = Product::all();
        $customers = Customer::all();
        return view('backend.orders.edit', compact('order', 'products', 'customers', 'details', 'total'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);
        $total = 0;
        if($request->has('update')){
            $this->validate($request, $this->rules);
            $order->fill($request->all());
            $order->save();
            return redirect()->back()->with('success', 'Orden modificada exitosamente');
        }
        else if($request->has('add')){
            $this->validate($request, ['quantity' => 'required|numeric|integer|min:1']);
            $detail = new OrderDetail();
            $detail->quantity = $request->quantity;
            $detail->product_id = $request->product_id;
            $detail->subtotal = $detail->product->price * $request->quantity;
            foreach ($order->details as $d){
                if($d->product_id == $detail->product_id){
                    $d->quantity += $detail->quantity;
                    $d->subtotal = $d->quantity * $d->product->price;
                    $d->save();
                    $order = Order::find($id);
                    foreach ($order->details as $detail){
                        $total += $detail->subtotal;
                    }
                    $order->total = $total;
                    $order->save();
                    return redirect()->back()->withInput()->with('success', 'Detalle agregado exitosamente');
                }
            }
            $detail->order_id = $id;
            $detail->save();
            $order = Order::find($id);
            foreach ($order->details as $detail){
                $total += $detail->subtotal;
            }
            $order->total = $total;
            $order->save();
            return redirect()->back()->withInput()->with('success', 'Detalle agregado exitosamente');
        }
        else if($request->has('quit')){
            $detail = OrderDetail::find($request->id);
            $detail->delete();
            $order = Order::find($id);
            foreach ($order->details as $detail){
                $total += $detail->subtotal;
            }
            $order->total = $total;
            $order->save();
            return redirect()->back()->with('success', 'Detalle eliminado exitosamente');
        }
        else if($request->has('deliver')){
            $order = Order::find($id);
            $order->status = 'delivered';
            $details = $order->details;
            foreach ($details as $detail){
                $detail->product->stock -= $detail->quantity;
                $detail->product->save();
            }
            $order->save();
            return redirect()->back()->with('success', 'Estatus de pedido modificado exitosamente');

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/orders/create.blade.php
@extends('generals.main')
@section('content')
    <h1>Ingresar Pedido</h1>
    {{Form::open(['route' => 'order.store', 'method' => 'post'])}}
        @include('backend.orders.partials.inputs')
        <div class="row">
            <div class="col-lg-4">
                <select class="form-control" name="product_id">
                    @foreach($products as $product)
                        <option value="{{$product->id}}">{{$product->design->name}} - {{$product->size}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-4">
                <input type="text"  class="form-control" name="quantity" placeholder="Cantidad">
            </div>
            <div class="col-lg-4">
                <input type="submit" name="add" value="Agregar" class="btn btn-primary">
            </div>
            @include('backend.orders.partials.tableDetails')
            <div class="row">
                <div class="col-lg-4">
                    <label>Total</label>
                    <input type="text" value="{{$total}}" class="form-control" name="total" readonly>
                </div>
            </div>
            <input type="submit" name="insert" value="Guardar" class="btn btn-success">

        </div>
    {{Form::close()}}
@endsection

resources/views/backend/orders/edit.blade.php
@extends('generals.main')
@section('content')
    <h1>Editar Pedido</h1>
    {{Form::open(['route' => ['order.update', $order->id], 'method' => 'put'])}}
        @include('backend.orders.partials.inputs')
        <div class="row">
            <div class="col-lg-4">
                <select class="form-control" name="product_id">
                    @foreach($products as $product)
                        <option value="{{$product->id}}">{{$product->design->name}} - {{$product->size}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-lg-4">
                <input type="text"  class="form-control" name="quantity" placeholder="Cantidad">
            </div>
            <div class="col-lg-4">
                <input type="submit" name="add" value="Agregar" class="btn btn-primary">
            </div>
            @include('backend.orders.partials.tableDetails')
            <div class="row">
                <div class="col-lg-4">
                    <label>Total</label>
                    <input type="text" value="{{$total}}" class="form-control" name="total" readonly>
                </div>
            </div>
            <input type="submit" name="update" value="Guardar" class="btn btn-success">

        </div>
    {{Form::close()}}
@endsection

resources/views/backend/orders/index.blade.php
@extends('generals.main')
@section('content')
    <h1>Pedidos</h1>
    <div class="col-lg-6">
        <br><a href="{{route('order.create')}}"><button class="btn btn-lg btn-success">Nuevo</button></a><br><br>
    </div>
    @include('backend.orders.partials.table')
    <div class="clearfix"></div>
@endsection